[[headers]]
  for = "/*"
  [headers.values]
    Gym-Custom = "true"
    Gym-Context = "develop"
    Gym-Branch = "develop"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "noindex"
