[build]
  command = "npm run build" # runs with ENV=production
  publish = "dist"

# [[headers]]
#   for = "/favicon/*"
#     [headers.values]
#     Access-Control-Allow-Origin = "*"
# [[headers]]
#   for = "/feeds/*"
#     [headers.values]
#     Access-Control-Allow-Origin = "*"
# [[headers]]
#   for = "/manifest.json"
#     [headers.values]
#     Access-Control-Allow-Origin = "*"
# [[headers]]
#   for = "*.js"
#   [headers.values] # cache for 1 year
#     Access-Control-Allow-Origin = "*"
#     Cache-Control = "public, max-age=31536000"
# [[headers]]
#   for = "*.css"
#   [headers.values] # cache for 1 year
#     Access-Control-Allow-Origin = "*"
#     Cache-Control = "public, max-age=31536000"
# [[headers]]
#   for = "/*.(svg|jpg|jpeg|png|gif|webp|ico|ttf|ttc|otf|eot|woff|woff2)"
#   [headers.values] # cache for 1 year
#     Access-Control-Allow-Origin = "*"
#     Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]

[[edge_functions]]
function = "eleventy-edge"
path = "/*"

[context.tutor-dev]
NODE_ENV="tutor-dev"
ELEVENTY_ENV="tutor-dev"

[context.tutor-local]
NODE_ENV="tutor-local"
ELEVENTY_ENV="tutor-local"

[context.soy]
NODE_ENV="soy"
ELEVENTY_ENV="soy"

[context.dev.environment]
NODE_ENV="development"
ELEVENTY_ENV="development"

# Local dev settings
[dev]
  # framework = "#static"
  port=8888
  targetPort=4040

# Per-branch settings (except production)
[context.branch-deploy]
command = "cat ./custom-headers/_global ./custom-headers/_branch-deploy > ./public/_headers && npm run build"

# Deploy preview settings
[context.deploy-preview]
command = "cat ./custom-headers/_global ./custom-headers/_deploy-preview > ./public/_headers && npm run build"

[context.develop]

[context.staging]

# Production settings
# [context.production]
# command = "npm run build && cat ./custom-headers/_global ./custom-headers/_production > ./custom-headers/_headers && cp ./custom-headers/_headers ./dist/_headers"
