meta:
  title: Gymnasium
  subtitle: Free online courses on design and development.
  author: Aquent Gymnasium
  description: Design a career you love with free online courses on design, development, accessibility, prototyping, UX, and career skills.
  og_img: /img/brand/og/gym-brand-og.png
  twitter_handle: "@AquentGymnasium"
navigation:
  main:
  - title: Courses
    href: GYM_ROOT_URL/courses/
  - title: Jobs
    href: GYM_ROOT_URL/jobs/
  - title: About
    href: GYM_ROOT_URL/about/
  auth:
    public:
    - title: Sign In
      href: GYM_LMS_URL/login
    - title: Sign Up
      href: GYM_LMS_URL/register
      class: btn
    private:
    - title: Dashboard
      href: GYM_LMS_URL/dashboard
    - title: Log Out
      href: GYM_LMS_URL/logout
  courses:
    - title: Full Courses
      href: GYM_ROOT_URL/courses/full/
    - title: Gym Shorts
      href: GYM_ROOT_URL/courses/short/
    - title: Take 5 Tutorials
      href: GYM_ROOT_URL/tutorials/
    - title: Collections
      href: GYM_ROOT_URL/collections/
  footer:
    tagline: Design a career you love with free online courses.
    sections:
      - label: What We Do
        links:
          - label: Courses
            href: GYM_ROOT_URL/courses/
          - label: Tutorials
            href: GYM_ROOT_URL/tutorials/
          - label: Jobs
            href: GYM_ROOT_URL/jobs/
          - label: Articles
            href: GYM_ROOT_URL/blog/
          - label: Livestreams
            href: https://www.youtube.com/@AquentGymnasium/streams
            target: _blank
            rel: noopener
          - label: Webinars
            href: GYM_ROOT_URL/webinars/
          - label: About
            href: GYM_ROOT_URL/about/
      - label: Content Collections
        links:
          - label: Design Systems
            href: GYM_ROOT_URL/design-systems/
          - label: Development
            href: GYM_ROOT_URL/development/
          - label: UX Design
            href: GYM_ROOT_URL/ux-design/
          - label: Prototyping
            href: GYM_ROOT_URL/prototyping/
          - label: Accessibility
            href: GYM_ROOT_URL/accessibility/
          - label: Career Skills
            href: GYM_ROOT_URL/career-skills/
      - label: Resources
        links:
          - label: FAQ
            href: GYM_ROOT_URL/faq/
          - label: Support
            href: GYM_ROOT_URL/support/
          - label: Social Impact
            href: GYM_ROOT_URL/social-impact/
          - label: Privacy Policy
            href: GYM_ROOT_URL/privacy-policy/
            rel: privacy-policy
          - label: Corporate Social Responsibility
            href: https://aquent.com/csr-policy
            target: _blank
            rel: noopener
          - label: Impressum
            href: https://aquent.de/impressum
            target: _blank
            rel: noopener
      - label: Social
        links:
          - label: Twitter
            href: https://twitter.com/AquentGymnasium
          - label: Facebook
            href: https://www.facebook.com/aquentgymnasium/
          - label: Instagram
            href: https://www.instagram.com/aquent_gymnasium/
          - label: YouTube
            href: https://www.youtube.com/channel/UCsAAa0dL-ZJpq4gN1zEcXYw
          - label: LinkedIn
            href: https://www.linkedin.com/school/gymnasium/
          - label: Medium
            href: https://medium.com/gymnasium
          - label: Github
            href: https://github.com/gymnasium
          - label: TikTok
            href: https://tiktok.com/@aquentgymnasium
      - label: Affiliated Sites
        links:
          - label: Aquent
            href: https://aquent.com
            target: _blank
            rel: noopener
          - label: Aquent Talent
            href: https://aquenttalent.com
            target: _blank
            rel: noopener
          - label: Aquent Studios
            href: https://aquentstudios.com
            target: _blank
            rel: noopener
          - label: Aquent RoboHead
            href: https://www.robohead.net
            target: _blank
            rel: noopener
          - label: Aquent Scout
            href: https://aquentscout.com
            target: _blank
            rel: noopener
      - label: Dev Links
        links:
          - label: Gymnasium (Production)
            href: https://thegymnasium.com
          - label: Gym Soy Data
            href: GYM_DATA_URL
          - label: Gym LMS
            href: GYM_LMS_URL
feeds:
  blog: https://medium.com/feed/gymnasium
logos:
  main:
    white:
      src: /img/brand/png/gymnasium-logo-white-4x.png
      srcset: /img/brand/svg/gymnasium-logo-white.svg
    black:
      src: /img/brand/png/gymnasium-logo-black-lg.png
      srcset: /img/brand/svg/gymnasium-logo-black.svg
  openedx:
    src: /img/brand/png/edx-openedx-logo-tag-dark.png
  tutor:
    src:
colors:
  primary: "#0077c8"
  secondary: "#ff5f14"
  white: "#fff"
  light-gray: "#ccc"
  gray: "#a6a6a6"
  medium-gray: "#737373"
  dark-gray: "#444"
  black: "#181818"
css:
  lms: /css/theme.css
  mfe: /css/mfe.css
messages:
  mfe:
    authn:
      welcome: "<p>This is an example of a welcome message on the registration page.</p>"

  theme:
    custom: "<p>This is an example of a custom message for anywhere in the theme.</p>"
