meta: 
  title: Gymnasium
  subtitle: Free online courses on design and development
  author: Aquent Gymnasium
  description: Design a career you love with free online courses on design, development, accessibility, prototyping, UX, and career skills.
  og_img: /img/brand/og/gym-brand-og.png
  twitter_handle: "@AquentGymnasium"
navigation:
  main:
  - title: Courses
    href: GYM_ROOT_URL/courses/
  - title: Jobs
    href: GYM_ROOT_URL/jobs/
  - title: About
    href: GYM_ROOT_URL/about/
  auth:
    public:
    - title: Sign In
      href: GYM_LMS_URL/login
    - title: Sign Up
      href: GYM_LMS_URL/register
      type: button
    private:
    - title: Dashboard
      href: GYM_LMS_URL/dashboard
    - title: Log Out
      href: GYM_LMS_URL/logout
  courses:
    - title: Full Courses
      href: GYM_ROOT_URL/courses/full/
    - title: Gym Shorts
      href: GYM_ROOT_URL/courses/short/
    - title: Take 5 Tutorials
      href: GYM_ROOT_URL/tutorials/
    - title: Collections
      href: GYM_ROOT_URL/collections/
  footer:
  - title: What We Do
    links:
      - title: Courses
        href: GYM_ROOT_URL/courses/
      - title: Tutorials
        href: GYM_ROOT_URL/tutorials/
      - title: Jobs
        href: GYM_ROOT_URL/jobs/
      - title: Webinars
        href: GYM_ROOT_URL/webinars/
      - title: Articles
        href: GYM_ROOT_URL/blog/
      - title: About
        href: GYM_ROOT_URL/about/
  - title: Content Collections
    links:
      - title: Design Systems
        href: GYM_ROOT_URL/design-systems/
      - title: Development
        href: GYM_ROOT_URL/development/
      - title: UX Design
        href: GYM_ROOT_URL/ux-design/
      - title: Prototyping
        href: GYM_ROOT_URL/prototyping/
      - title: Accessibility
        href: GYM_ROOT_URL/accessibility/
      - title: Career Skills
        href: GYM_ROOT_URL/career-skills/
  - title: Resources
    links:
      - title: FAQ
        href: GYM_ROOT_URL/faq/
      - title: Support
        href: GYM_ROOT_URL/support/
      - title: Social Impact
        href: GYM_ROOT_URL/social-impact/
      - title: Privacy Policy
        href: GYM_ROOT_URL/privacy-policy/
      - title: Corporate Social Responsibility
        href: https://aquent.com/csr-policy
        target: _blank
        rel: noopener
      - title: Impressum
        href: https://aquent.de/impressum
        target: _blank
        rel: noopener
  - title: Social
    links:
      - title: Twitter
        href: https://twitter.com/AquentGymnasium
      - title: Facebook
        href: https://www.facebook.com/aquentgymnasium/
      - title: Instagram
        href: https://www.instagram.com/aquent_gymnasium/
      - title: YouTube
        href: https://www.youtube.com/channel/UCsAAa0dL-ZJpq4gN1zEcXYw
      - title: LinkedIn
        href: https://www.linkedin.com/school/gymnasium/
      - title: Medium
        href: https://medium.com/gymnasium
      - title: Github
        href: https://github.com/gymnasium
      - title: TikTok
        href: https://tiktok.com/@aquentgymnasium
  - title: Affiliated Sites
    links:
      - title: Aquent
        href: https://aquent.com
        target: _blank
        rel: noopener
      - title: Aquent Talent
        href: https://aquenttalent.com
        target: _blank
        rel: noopener
      - title: Aquent Studios
        href: https://aquentstudios.com
        target: _blank
        rel: noopener
      - title: Aquent RoboHead
        href: https://www.robohead.net
        target: _blank
        rel: noopener
      - title: Aquent Scout
        href: https://aquentscout.com
        target: _blank
        rel: noopener
  - title: Dev Links
    links:
      - title: Gymnasium (Production)
        href: https://thegymnasium.com
      - title: Gym Soy Data
        href: GYM_DATA_URL
      - title: Gym LMS
        href: GYM_LMS_URL
feeds:
  blog: https://medium.com/feed/gymnasium
logos:
  main:
    white:
      src: /img/brand/png/gymnasium-logo-white-4x.png
      srcset: /img/brand/svg/gymnasium-logo-white.svg
    black:
      src: /img/brand/png/gymnasium-logo-black-lg.png
      srcset: /img/brand/svg/gymnasium-logo-black.svg
  openedx:
    src: /img/brand/png/edx-openedx-logo-tag-dark.png
  tutor:
    src:
colors:
  primary: "#0077c8"
  secondary: "#ff5f14"
  white: "#fff"
  light-gray: "#ccc"
  gray: "#a6a6a6"
  medium-gray: "#737373"
  dark-gray: "#444"
  black: "#181818"
css:
  lms: /css/theme.css
  mfe: /css/mfe.css
messages:
  mfe:
    authn:
      welcome: "<p>This is an example of a welcome message on the registration page.</p>"
      
  theme:
    custom: "<p>This is an example of a custom message for anywhere in the theme.</p>"
