meta:
  id: COL-001
  title: "Development"
  topic: "Development"
  description: "Develop the skills you need to build fast, responsive websites."
  slug: development
  order: 2
  redirectFrom: '/web-development/'

header:
  header_id: # default is null
  header_class: # default is null
  heading_type: h1 # h1-h6, default is h2
  heading_class: # default is caps
  heading_id: # default is null
  heading: Development
  description: |
    <p>Gymnasium offers free online development <a href="#courses"><b>courses</b></a>, <a href="#tutorials"><b>tutorials</b></a>, <a href="#webinars"><b>webinars</b></a>, <a href="#articles"><b>articles</b></a>, and <a href="#jobs"><b><span class="visuallyhidden">development </span> jobs</b></a> through Aquent.</p>

courses:
  module: lists/image-course
  header:
    heading: "Web Development Courses"
    description: Learn web development with industry experts.
  cta:
    href: /courses/
    label: View More Courses
    class: btn
  dev-courses:
    schema: true
    ids:
    - id: GYM-107
    - id: GYM-109
    - id: GYM-016
    - id: GYM-011
    - id: GYM-007
    - id: GYM-004
    - id: GYM-009
    - id: GYM-104
    - id: GYM-108
    - id: GYM-012
    - id: GYM-006
    - id: GYM-014


tutorials:
  module: lists/image-course
  header:
    heading: "Development Tutorials"
    description: Learn a development skill in 5 minutes.
  cta:
    href: /courses/take5/
    label: View More Tutorials
    class: btn
  dev-tutorials:
    ids:
    - id: GYM-5001
    - id: GYM-5002
    - id: GYM-5003
    - id: GYM-5004
    - id: GYM-5005
    - id: GYM-5006

webinars:
  module: lists/image-course
  header:
    heading: Development Webinars
    description: Insightful conversations with trailblazers in the web community.
  cta:
    href: /webinars/
    label: View More Webinars
    class: btn
  dev-webinars:
    ids:
    - id: web0013
    - id: web0011
    - id: web0010
    - id: web0009
    - id: web0008
    - id: web0007
    - id: web0006
    - id: web0005
    - id: web0004

articles:
  module: lists/default
  header:
    heading: "Development Articles"
  development:
    links:
    - label: "Brad Frost on How (and Why) to Use Pattern Lab"
      href: "https://medium.com/gymnasium/brad-frost-on-how-and-why-to-use-pattern-lab-49607f89d7f0"
    - label: "Adaptability As the Key to Success in Design"
      href: "https://medium.com/gymnasium/adaptability-as-the-key-to-success-in-design-ea64c1ed4044"
    - label: "4 Reasons Web Designers Should Learn to Code"
      href: "https://medium.com/gymnasium/4-reasons-web-designers-should-learn-to-code-2d1770d7866d"
    - label: "3 Tips for Chrome DevTools Users"
      href: "https://medium.com/gymnasium/three-tips-for-chrome-devtools-users-b1bbbc07daab"
    - label: "CSS Grid Layout: A Cornucopia of Options"
      href: "https://medium.com/gymnasium/css-grid-layout-a-cornucopia-of-options-90a5ee10ad9f"
    - label: "A Year of Gymnasium on Open edX"
      href: "https://medium.com/gymnasium/a-year-of-gymnasium-on-open-edx-2f0c6df2afee"
    - label: "Experts Agree: Web Design is Hard"
      href: "https://medium.com/gymnasium/experts-agree-web-design-is-hard-42dd883b42ef"

jobs:
  module: jobs
  header:
    heading: "Development Jobs"
